sudo: required

services:
  - docker

arch:
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  before_install:
  - "sudo mkdir /run/shm"
  script:
  - "sudo /build/build.sh -v"
  
script:
- "travis_wait 30 sleep 1800 &"
- "sudo bash arch-travis.sh"
- "ls"

before_deploy:
  - sudo mv out/*.iso .
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

deploy:
  - provider: releases
    skip_cleanup: true
    draft: true
    api_key:
      secure: "d+P4AUNSteNe32bktUwgJlOtxcJXJJIdGcZNNRn+uz8D3kYsR0Dpqjh659oDhWW/TuUiyntOMyRk6t4+gJcHzz5sjxPJNmjRTb3XQqKfbnlYiIY+zqUXNO3LwfUGQRRNJXTmI5dYWRMLGl4T0nVjrMIRJqKRvTm3cggSo/oyT/GHWdXCXbksj/ayjR2xb8XVDUVOpCingi9SI6qqk1ckJNPPDUiSrvzwGSY6FmSy8tV/fBy2jeCNmPzbTX+rt7wRrzhLw4hMGLN0cHadZvcXTI1/hxSAoeHdHgljMaKHCRr+U4sf3NbS9wXRexjb64+aaFT9L84VG5a/GzFdxjR9OJSv7MBGhF6Eb/pM8sxB4WRl0EmOVmU1/kMxOK1G/Dyp1V0bhUGv9zVklseFXrQHY7/OyetAI3B8E6IGGm6YkqlTN0Mvl34EDJiRm2Wq/KdXSXFgzj6jR+Cotv63r+6YtNSgIeVT7uMvf3t74eMbN58mUSyRufv3YM+0SU5o0EJ3OKlTQC6uDsbqp0aXGb3jPdNUc/Fs3lwqhHvtz4UbAwxxIqN8r4APM8tDVhp0vt74bbsfa/cbRke9c0kFYJCX/QMRopqgiVxvppnZPB4QKMr35qMjMzB7YDL0SAcLP/PidnPyCbwqd2Ob361eJX6YE1L2zkosLS4R/MQN+bhaweo="
 #https://docs.travis-ci.com/user/encryption-keys/
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: 
     - "/home/travis/${image_name}" #for future we can have multiple files so doing like this
    on:
      all_branches: true
